=== Acidburn0zzz/tinos/projects/rina/rina.demo.mib/src/main/resources/mib.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://pouzinsociety.org/rina/mib"
	xmlns:tns="http://pouzinsociety.org/rina/mib" elementFormDefault="qualified">

	<element name="mibRoot" type="tns:mibNode">
		<annotation>
			<documentation>
				The root node of the mib
			</documentation>
		</annotation>
	</element>

	<complexType name="mibNode" mixed="true">
		<annotation>
			<documentation>
				Represents a node in the MIB. The MIB has a tree
				structure and therefore MIB nodes can have nested nodes. The node is
				uniquely identified by the fully qualified object name (concatenation 
				of name elements from the root to the mib node, with '\0' between 
				each part) + objectClass combination. In some environments, like DIFs, 
				the FQON is sufficient to unambiguously identify a node in the MIB.
			</documentation>
		</annotation>
		<sequence>
			<element name="objectClass" type="string" minOccurs="0"
				maxOccurs="1">
				<annotation>
					<documentation>
						The objectclass blabla
						</documentation>
				</annotation>
			</element>
			<element name="description" type="string" minOccurs="0"
				maxOccurs="1">
				<annotation>
					<documentation>
						The description blabla
						</documentation>
				</annotation>
			</element>
			<element name="memberACL" type="string" minOccurs="0"
				maxOccurs="1">
				<annotation>
					<documentation>
						The description blabla
						</documentation>
				</annotation>
			</element>
			<element name="childNode" type="tns:mibNode" minOccurs="0" maxOccurs="unbounded">
				<annotation>
					<documentation>
						The children of this mibNode.
						</documentation>
				</annotation>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required">
			<annotation>
				<documentation>
					The name of the node in the MIB (not the fully qualified object mname)
				</documentation>
			</annotation>
		</attribute>
		<attribute name="id" type="integer" use="required">
			<annotation>
				<documentation>
					The id blablalba
				</documentation>
			</annotation>
		</attribute>
	</complexType>

</schema>

=== Acidburn0zzz/tinos/projects/rina/rina.demo.mib/src/main/resources/dafmib.xml
<?xml version="1.0" encoding="UTF-8"?>
<mibRoot xmlns="http://pouzinsociety.org/rina/mib"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pouzinsociety.org/rina/mib mib.xsd" name="daf" id="1">
	<childNode name="resourceallocator" id="1">
		<objectClass>daf.ResourceAllocator</objectClass>
	</childNode>
	<childNode name="ribdaemon" id="2">
		<objectClass>daf.RibDaemon</objectClass>
		<description></description>
	</childNode>
	<childNode name="ipc" id="3">
		<objectClass>daf.IPC</objectClass>
		<description>The component that manages IPC</description>
		<childNode name="multiplexing" id="1">
			<objectClass>daf.ipc.Multiplexing</objectClass>
			<description></description>
		</childNode>
		<childNode name="sduprotection" id="2">
			<objectClass>daf.ipc.SduProection</objectClass>
			<description></description>	
		</childNode>
	</childNode>
	<childNode name="management" id="4">
		<objectClass>daf.management</objectClass>
		<description>The management component of the application process</description>
		
		
		
		
		<childNode name="naming" id="1">
			<objectClass>daf.management.Naming</objectClass>
			<description>The naming information of this application process (name, synonyms, whatevercast)</description><childNode name="applicationprocessname" id="1">
			<objectClass>daf.management.ApplicationProcessName</objectClass>
			<description>The name of the application process</description>
		</childNode><childNode name="currentsynonym" id="2">
			<objectClass>daf.management.ApplicationProcessNameSynonym</objectClass>
			<description>The current synonym of the application process names, i.e. its address</description>
		</childNode><childNode name="synonyms" id="3">
			<objectClass>daf.management.ApplicationProcessNameSynonym[]</objectClass>
			<description>All the synonyms of the application process name</description>
		</childNode><childNode name="whatevercast" id="4">
			<objectClass>daf.management.WhatevercastName[]</objectClass>
			<description>The whatevercast names that the application process knows about</description>
		</childNode></childNode>
		<childNode name="enrollment" id="2">
			<objectClass>daf.management.Enrollment</objectClass>
			<description>All the enrollment information (names of the members of the DIF and their addresses?)</description></childNode>
		<childNode name="operationalstatus" id="3">
			<objectClass>daf.management.OperationalStatus</objectClass>
			<description>The operational status of the application process</description></childNode>
	</childNode>
</mibRoot>
